### ISSUE TITLE
Saving FM sectors although I specified -e 3

### ISSUE THREAD

**Issue by MattisLind** [qbarnes/cw2dmk#23]
I use this command to dump a problematic RX02  disks:

cw2dmk -d 1 -t 77 -j -x 20 -s 1 -e 3 file.dmk

Since I specified that the encoding is RX02 I think that it should always store RX02 sectors. But in reality it stores FM sectors.

So the latest dumped disk got 1999 RX02 sectors and three FM sectors stored. I think I would be better off with a three bad RX02 sectors stored which I could manually investigate.

**Comment by qbarnes** [comment]
Did you / can you capture a Level 7 log (e.g. add `-v 72` to the `cw2dmk` command) while reading the floppy then put the `file.log` and `file.dmk` somewhere we can access them (or mail them to us)?

That'll help Tim and/or me sort out what's going on.

**Comment by MattisLind** [comment]
Hello!

Here is a link to a [logfile](https://drive.google.com/file/d/1nzELhfpfGicmLj00oxiBpldnCjWs4R5y/view?usp=sharing) and the resulting [image](https://drive.google.com/file/d/1dmTiyAJFvupr2T9KxhKBeZ6iQPA9hIYo/view?usp=sharing).

**Comment by TimothyPMann** [comment]
It looks like I assigned this to myself and then forgot about it. At least I don't remember it and can't find email about it. Oops.

**Comment by TimothyPMann** [comment]
Sorry I forgot about this. It seems to be a bug in the -j feature. When two track reads are combined, the "reused" sectors are reported in the summary at the end as being FM.

I'm not sure yet if this is just a bug in printing the summary or if the -j feature made a mess of the image. I'll dig in further.

**Comment by TimothyPMann** [comment]
p.s. I'm pretty sure the DMK image is valid, so this bug is not serious. I hacked up dmk2jv3 to check the CRCs, and they all came out correct.

I'm not too familiar with the -j code. Will have to read it carefully to figure out why reused RX02 sectors get counted as FM.

**Comment by TimothyPMann** [comment]
I see what the bug is.  The encoding for the current sector is captured in the enc_sec[] array too soon, in dmk_idam. The way RX02 format works, the IDAM, ID address block, and DAM are always encoded as FM. Only the sector data that begins right after each DAM and extends through the CRC is encoded in RX02-modified MFM.

**Comment by MattisLind** [comment]
Thanks a lot for fixing this!
